version: "3"
services:
  appserver:
    container_name: pyserver
    env_file:
      - .env
    hostname: localhost
    image: basic_python
    ports:
      - "5000:5000"
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true
